projects:
  editor-api:
    schema:
      - 'apps/api-example/schema-v1-admin.graphql'
    documents: 'libs/editor/api/**/*.graphql'
  editor-api-v2:
    schema:
      - 'apps/api-example/schema-v2.graphql'
    documents: 'libs/editor/api-v2/**/*.graphql'
  website-api:
    schema:
      - 'apps/api-example/schema-v2.graphql'
    documents:
      - 'libs/website/api/**/*.graphql'
      - 'libs/website/api/**/graphql.ts'
  testing:
    schema:
      - 'apps/api-example/schema-v2.graphql'
    documents:
      - 'libs/testing/src/graphql/public/graphql-public.ts'
      - 'libs/testing/src/graphql/public/**/*.graphql'
