{{- if and (eq .Values.routing.type "route") .Values.routing.route.enabled -}}
{{- $fullName := include "helm.fullname" . -}}
---
# Website Route
{{- $websiteUrl := urlParse .Values.deployment.env.WEBSITE_URL }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}-website
  labels:
    app.kubernetes.io/name: {{ include "helm.name" . }}
    helm.sh/chart: {{ include "helm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: website
    {{- with .Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.routing.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ $websiteUrl.host }}
  {{- if $websiteUrl.path }}
  path: {{ $websiteUrl.path }}
  {{- end }}
  to:
    kind: Service
    name: {{ $fullName }}-website
    weight: 100
  port:
    targetPort: http
  {{- if .Values.routing.route.tls.enabled }}
  tls:
    termination: {{ .Values.routing.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.routing.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
