name: Publish on tags

on:
  create:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Use NodeJS 12"
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: "Yarn install"
        run: |
          yarn install
          git diff
          git reset --hard

      - if: "contains(github.ref, 'alpha')"
        name: "Publish next npms"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn run publish:next --yes

      - if: "!contains(github.ref, 'alpha')"
        name: "Publish latest npms"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: yarn run publish --yes
