name: Publish docker images

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set RELEASE_VERSION env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set RELEASE_DATE env
        run: echo "RELEASE_DATE=$(date +%s)" >> $GITHUB_ENV

      - if: | 
          github.event_name == 'pull_request'
        name: "Build and push on pull-request"
        uses: docker/build-push-action@v2
        with:
          target: production
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:${{ github.sha }}

      - if: | 
          github.event_name == 'pull_request'
        name: "Deploy pull-request"
        uses: ./.github/workflows/deploy.yml
        with:
          image: ghcr.io/wepublish/wepublish:${{ github.sha }}


      - if: |
          github.ref == 'refs/heads/master'
        name: "Build and push on master"
        uses: docker/build-push-action@v2
        with:
          target: dev
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:master-${{ env.RELEASE_DATE }}-${{ github.sha }}

      - if: |
          contains(github.ref, 'tags/') && contains(github.ref, 'alpha')
        name: "Build and push on alpha release"
        uses: docker/build-push-action@v2
        with:
          target: production
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:${{ env.RELEASE_VERSION }}

      - if: |
          contains(github.ref, 'tags/') && !contains(github.ref, 'alpha')
        name: "Build and push on non-alpha tag"
        uses: docker/build-push-action@v2
        with:
          target: production
          push: true
          tags: |
            ghcr.io/wepublish/wepublish:${{ env.RELEASE_VERSION }}
            ghcr.io/wepublish/wepublish:latest

