name: Release helm chart

on:
  push:
    branches:
      - 'master'
    paths:
      - 'helm/charts/**/*'

jobs:
  app-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: goodsmileduck/helm-push-action@v2
        env:
          SOURCE_DIR: 'helm/charts'
          CHART_FOLDER: 'wepublish'
          FORCE: 'True'
          CHARTMUSEUM_URL: 'https://gitlab.com/api/v4/projects/38941346/packages/helm/stable'
          CHARTMUSEUM_USER: 'wepublish'
          CHARTMUSEUM_PASSWORD: ${{ secrets.GITLAB_HELM_TOKEN }}


