name: Review

on:
  pull_request:
    types: [ opened, synchronize, reopened]

jobs:
  publish-docker-image:
    name: Docker
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      tags: |
        ghcr.io/wepublish/wepublish:${{ github.sha }}
    secrets: inherit

  review_deployment:
    name: Deployment
    uses: ./.github/workflows/review-deployment.yml
    needs: publish-docker-image
    with:
      image: ghcr.io/wepublish/wepublish:${{ github.sha }}
    secrets: inherit
